// Package ebpf is the Constellation runtime-agent's kernel data-plane for
// process and file events. CO-RE eBPF programs emit process-exec and
// file-open events into a Go channel via a userspace ring-buffer reader.
//
// On a Linux 6.x host with BTF (/sys/kernel/btf/vmlinux) the agent attaches:
//
//   - exec / execveat tracepoints (sched_process_exec)  →  ProcessEvent
//   - LSM security_file_open (BPF_PROG_TYPE_LSM)         →  FileEvent
//
// Wave 7 retired the tcp_connect / inet_csk_accept kprobes that used to feed
// NetworkEvent. The network observation path lives in internal/runtime/dp
// (the NeuVector C data-plane), which provides real on-wire byte counters,
// per-session aggregation, DPI-derived L7 detection, policy verdicts, and
// signature-based threat detection — strictly more than the kprobe-based
// connect-event capture this package previously shipped. NetworkEvent and
// EventKindNetwork remain in this package as exported types but are no
// longer emitted from the kernel decoder.
//
// Programs live in bpf/runtime.bpf.c and are compiled out-of-tree (see Makefile) into
// CO-RE object files that the loader picks up via `go:embed`. We intentionally do NOT
// invoke bpf2go at `go generate` time from inside this package — that requires clang +
// libbpf headers on every developer machine and breaks `go build ./...` on a fresh
// checkout. Instead the embedded object is regenerated by `make ebpf-objs` (see the
// repo Makefile) and committed.
//
// Userspace API:
//
//	agent, err := ebpf.New(ebpf.Options{Logger: slog.Default()})
//	if err != nil { return err }
//	defer agent.Close()
//
//	if err := agent.Run(ctx); err != nil { ... }
//	for evt := range agent.Events() { ... }
//
// The Run loop blocks until ctx is cancelled. Events() is a typed channel of `Event`
// (a sum type — exactly one of {Process,Network,File} is set). The channel is closed
// when Run returns.
//
// On non-Linux platforms (and on Linux when the kernel lacks BTF / the binary is not
// privileged) New returns a degraded agent that produces no events but otherwise
// satisfies the same interface — callers can run the rest of the runtime pipeline
// against a synthetic event source.
package ebpf
