version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-nonmajor:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-production-nonmajor:
        dependency-type: production
        patterns: ["*"]
        update-types: [minor, patch]
      frontend-development-nonmajor:
        dependency-type: development
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-nonmajor:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /tools/vscode-extension
    schedule:
      interval: weekly
    groups:
      extension-nonmajor:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: pip
    directory: /tools/constellation-test-suite
    schedule:
      interval: weekly
    groups:
      python-nonmajor:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: weekly
    groups:
      docker-nonmajor:
        patterns: ["*"]
        update-types: [minor, patch]
