"""Constellation deployer.

Given a Cluster (the harness brought up or attached to), build all the
constellation images on the cluster's host, load them into the cluster's
container runtime, and helm-install the chart with test-friendly values.
"""
from __future__ import annotations

import base64
import os
import time
from pathlib import Path

from .cluster import Cluster
from .helm import Helm
from .kubectl import Kubectl


TEST_CLUSTER_ID = os.environ.get(
    "CONSTELLATION_TEST_CLUSTER_ID",
    "11111111-1111-1111-1111-111111111111",
)

# Image roles we expect the chart to need. Must match the Makefile's
# `images:` aggregate (post-Wave-E rename: <registry>/<role>:<tag>).
IMAGE_ROLES = [
    "api", "scanner", "operator", "discoverer", "admission", "frontend",
    "migrate", "runtime-agent", "audit-archiver", "bootstrap",
]

# Test values file we'll write on the cluster host. Single-replica
# everything, embedded postgres, no ingress.
TEST_VALUES_YAML = """\
# Generated by constellation-test-suite. Single-node test profile.
image:
  registry: ghcr.io/alphabravocompany/constellation
  tag: dev
  pullPolicy: IfNotPresent
api:
  enabled: true
  replicas: 1
  resources:
    limits:   { cpu: 1, memory: 1Gi }
    requests: { cpu: 100m, memory: 256Mi }
operator: { enabled: true, replicas: 1 }
discoverer: { enabled: true, replicas: 1 }
admission:
  enabled: true
  replicas: 1
  webhook:
    failurePolicy: Fail
  policies:
    enabled: true
    clusterId: "__TEST_CLUSTER_ID__"
  audit:
    enabled: true
    clusterId: "__TEST_CLUSTER_ID__"
auditArchiver: { enabled: false }
runtimeAgent: { enabled: true }
postgres: { embedded: true }
ingress: { enabled: false }
tls: { certManager: { enabled: false } }
clusterRegistration:
  enabled: true
  clusterId: "__TEST_CLUSTER_ID__"
  distro: "k3s"
""".replace("__TEST_CLUSTER_ID__", TEST_CLUSTER_ID)


def build_images(cluster: Cluster, *, source_dir: str = "/root/constellation") -> None:
    """Run `make images` on the cluster's host shell. Idempotent — docker
    cache makes a re-run fast.
    """
    # Ensure docker buildx builder exists.
    cluster.shell.run(
        "docker buildx create --name testsuite --use --bootstrap 2>&1 | tail -1 || "
        "docker buildx use testsuite 2>&1 | tail -1",
        check=False,
    )
    cluster.shell.run(
        f"cd {source_dir} && PLATFORMS=linux/amd64 make images",
        timeout=30 * 60,
    )


def load_images_into_cluster(cluster: Cluster, *, registry: str = "ghcr.io/alphabravocompany/constellation",
                             tag: str = "dev") -> None:
    """Load locally-built docker images into the cluster's container runtime.
    Path differs per cluster kind:
      - k3s: containerd; use `k3s ctr images import`
      - k3d: containerd in the k3d node containers; use `k3d image import`
      - kind: containerd in the kind node containers; use `kind load docker-image`
      - external: assume the registry is already accessible
    """
    if cluster.cluster_kind == "external":
        return
    for role in IMAGE_ROLES:
        ref = f"{registry}/{role}:{tag}"
        if cluster.cluster_kind == "k3s":
            cluster.shell.run(
                f"docker save {ref} | k3s ctr -n k8s.io images import -",
                timeout=300,
            )
        elif cluster.cluster_kind == "k3d":
            cluster.shell.run(
                f"k3d image import {ref} -c {cluster.name}",
                timeout=300,
            )
        elif cluster.cluster_kind == "kind":
            cluster.shell.run(
                f"kind load docker-image {ref} --name {cluster.name}",
                timeout=300,
            )


def write_test_values(cluster: Cluster, path: str = "/root/constellation-test-values.yaml") -> str:
    """Write the test values.yaml on the cluster host. Returns the path."""
    encoded = base64.b64encode(TEST_VALUES_YAML.encode()).decode()
    cluster.shell.run(f"echo {encoded} | base64 -d > {path}")
    return path


def helm_install(cluster: Cluster, *, source_dir: str = "/root/constellation",
                 release: str = "constellation",
                 namespace: str = "constellation-system") -> None:
    helm = Helm(cluster.shell)
    chart = f"{source_dir}/deploy/charts/constellation"
    values = write_test_values(cluster)
    helm.install(
        release=release,
        chart=chart,
        namespace=namespace,
        values_files=[values],
        wait=True,
        timeout="10m",
    )


def deploy(cluster: Cluster, *, source_dir: str = "/root/constellation",
           build: bool = True) -> None:
    """End-to-end: build → load → helm install. Returns when all pods are
    Ready AND the chart's auto-registered cluster row exists in the DB
    (otherwise tests that need a cluster_id race the operator's reconcile).
    """
    if build:
        build_images(cluster, source_dir=source_dir)
    load_images_into_cluster(cluster)
    helm_install(cluster, source_dir=source_dir)
    # Sanity wait — `helm install --wait` already waits for pods. Give the
    # bootstrap-job + post-install hooks a few extra seconds to settle; the
    # `clusters` row gets seeded by the conftest fixture if no discoverer
    # populates it. Don't fail here on missing row — that's an expected
    # state for the minimal test profile.
    time.sleep(5)


def teardown_release(cluster: Cluster, *, release: str = "constellation",
                     namespace: str = "constellation-system") -> None:
    helm = Helm(cluster.shell)
    helm.uninstall(release, namespace=namespace)
    Kubectl(cluster.shell).run_global(
        f"delete namespace {namespace} --ignore-not-found", check=False, timeout=120,
    )
