apiVersion: v2
name: constellation
description: Constellation — Container & Kubernetes Security Platform
type: application
version: 0.2.0
appVersion: "0.2.0"
kubeVersion: ">=1.27.0-0"
maintainers:
  - name: Alpha Bravo Security
home: https://github.com/alphabravo-oss/constellation
sources:
  - https://github.com/alphabravo-oss/constellation
keywords:
  - security
  - vulnerability-management
  - admission-control
  - runtime-security
  - kubernetes
